INSERT INTO roles (name)
SELECT 'ROLE_USER'
WHERE NOT EXISTS (SELECT name FROM roles WHERE name = 'ROLE_USER');

INSERT INTO roles (name)
SELECT 'ROLE_USER'
    WHERE NOT EXISTS (SELECT name FROM roles WHERE name = 'ROLE_MODERATOR');

INSERT INTO roles (name)
SELECT 'ROLE_USER'
    WHERE NOT EXISTS (SELECT name FROM roles WHERE name = 'ROLE_ADMIN');
-- INSERT INTO roles(name) VALUES('ROLE_USER');
-- INSERT INTO roles(name) VALUES('ROLE_MODERATOR');
-- INSERT INTO roles(name) VALUES('ROLE_ADMIN');