version: '3.8'

services:
  database:
    image: postgres:16
    restart: always
    expose:
      - 5432
    ports:
      - 5432:5432
    command: -p 5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=1234'

  app:
    image: 'spring-boot-docker:dockerfile'
    build:
      context: .
    container_name: app
    depends_on:
      - database
    ports:
      - 3001:8080
    environment:
      SPRING_APPLICATION_JSON: '{
              "spring.datasource.url"  : "jdbc:postgresql://database:5432/edtech_club",
              "spring.datasource.username" : "postgres",
              "spring.datasource.password" : "1234",
              "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
              "spring.jpa.hibernate.ddl-auto" : "update"
            }'
