name: build

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/edtech-app-backend:latest

      - name: Copy deploy file via ssh
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VM_HOST_PROD }}
          username: ${{ secrets.VM_USERNAME_PROD }}
          key: ${{ secrets.VM_PRIVATE_KEY_PROD }}
          port: ${{ secrets.VM_PORT_PROD }}
          source: "scripts/deploy.sh"
          target: "/root"

      - name: Execute remote ssh command
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM_HOST_PROD }}
          username: ${{ secrets.VM_USERNAME_PROD }}
          key: ${{ secrets.VM_PRIVATE_KEY_PROD }}
          port: ${{ secrets.VM_PORT_PROD }}
          script: export MAIL_PASS="${{ secrets.MAIL_PASS }}" && export POSTGRES_USERNAME="${{ secrets.POSTGRES_USERNAME }}" && export POSTGRES_PASSWORD="${{ secrets.POSTGRES_PASSWORD }}" && export FILES_PATH="${{ secrets.FILES_PATH }}" && docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_TOKEN }} && sh scripts/deploy.sh

